// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs4dDysA3t4MIu_BXiPnCFPK1Lg-zsTdM',
    appId: '1:22053364367:web:f031e3ab74ee56ae1cc6fa',
    messagingSenderId: '22053364367',
    projectId: 'flutterwithfirebase-fb743',
    authDomain: 'flutterwithfirebase-fb743.firebaseapp.com',
    storageBucket: 'flutterwithfirebase-fb743.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi7hnh_iMv55-lIPN4GI0sJAlH7ViYf_Y',
    appId: '1:22053364367:android:73164e77b3f68ed51cc6fa',
    messagingSenderId: '22053364367',
    projectId: 'flutterwithfirebase-fb743',
    storageBucket: 'flutterwithfirebase-fb743.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGpmyvEwuYx2B4MDE8dhtt_3NOpAuYJBc',
    appId: '1:22053364367:ios:4559895c34b67c7b1cc6fa',
    messagingSenderId: '22053364367',
    projectId: 'flutterwithfirebase-fb743',
    storageBucket: 'flutterwithfirebase-fb743.firebasestorage.app',
    iosBundleId: 'com.example.formOrderApp',
  );
}
